// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WPF_Market.Models;

public partial class Bought
{
    public int IDInvoice { get; set; }

    public int IDUser { get; set; }

    public DateTime DateBought { get; set; }

    public float TotalPrice { get; set; }

    public virtual User IDUserNavigation { get; set; }

    public virtual ICollection<LstProduct> LstProducts { get; set; } = new List<LstProduct>();
}