// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WPF_Market.Models;

public partial class Comment
{
    public int IDShop { get; set; }

    public int IDUser { get; set; }

    public DateTime DataTimeCreate { get; set; }

    public string Comment1 { get; set; }

    public float? Rate { get; set; }

    public int IDCmt { get; set; }

    public virtual Shop IDShopNavigation { get; set; }

    public virtual User IDUserNavigation { get; set; }
}