// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WPF_Market.Models;

public partial class LstImagesCMT
{
    public int IDComment { get; set; }

    public string ImageLink { get; set; }

    public virtual Comment IDCommentNavigation { get; set; }
}