// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WPF_Market.Models;

public partial class LstProduct
{
    public int IDInvoice { get; set; }

    public int IDProduct { get; set; }

    public int Number { get; set; }

    public virtual Bought IDInvoiceNavigation { get; set; }

    public virtual Inventory IDProductNavigation { get; set; }
}