// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WPF_Market.Models;

public partial class Priority
{
    public int IDuser { get; set; }

    public int IDproduct { get; set; }

    public int? NumPriority { get; set; }

    public virtual Inventory IDproductNavigation { get; set; }

    public virtual Account IDuserNavigation { get; set; }
}